name: Events Demo
on: [push, workflow_dispatch]
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Output
              run : echo "${{ toJSON(github) }}"
            - name: Output2
              env:
                GITHUB_CONTEXT: ${{ toJSON(github.email) }}
              run: echo "$GITHUB_CONTEXT"