name: Events Demo
on: [push, workflow_dispatch]
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Output
              run : echo "${{ toJSON(github) }}"
    output2:
        runs-on: ubuntu-latest
        steps:
            - name: Output2
              run : echo "${{ toJSON(github.email) }}"